name: 'Update Index'
on:
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * *'
jobs:
  update_index:
    name: 'Update Index'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          submodules: 'recursive'
      - name: 'Publish'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./action.sh
      - name: 'Update Index'
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: Update Index